### ISSUE TITLE
JSON::ParserError

### ISSUE THREAD

**Issue by gitviola** [bankscrap/bankscrap-bbva#5]
I'm receiving a `JSON::ParserError` when using this gem:

```
require 'bankscrap'
require 'bankscrap-bbva'

bbva = Bankscrap::BBVA::Bank.new(user: '......', password: '.......')

puts bbva.accounts.inspect
```

Here is the error output:
```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:156:in `parse': 743: unexpected token at '<logon/> (JSON::ParserError)
'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bankscrap-bbva-2.0.1/lib/bankscrap/bbva/bank.rb:49:in `fetch_accounts'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bankscrap-2.0.5/lib/bankscrap/bank.rb:30:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bankscrap-bbva-2.0.1/lib/bankscrap/bbva/bank.rb:20:in `initialize'
	from run.rb:4:in `new'
	from run.rb:4:in `<main>'
```

**Comment by gitviola** [comment]
Might this be related to https://github.com/bankscrap/bankscrap-bbva/blob/master/lib/bankscrap/bbva/bank.rb#L109 @javiercr? They also support NIE as logins, not just DNI. Not sure if this might be handled differently.

> The NIE consists of an 'X' or 'Y' followed by 7 or 8 digits then another letter.
> http://www.strongabogados.com/nie.php
> https://www.ordenacionjuego.es/en/calculo-digito-control
