### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by amiedes** [bankscrap/bankscrap-bbva#8]
Thanks for developing this gem :heart:, I was using a scrapper for this purpose but when I was told about this library I thought it was much more practical. I also found the video of the Madrid.rb talk very interesting.

I've stumpled accross the following error - when running:

```
bankscrap transactions BBVA --credentials=user:<user> password:<password>
```

I'm getting the following error:

```
Traceback (most recent call last):
	19: from /home/amiedes/.rbenv/versions/2.6.5/bin/bankscrap:23:in `<main>'
	18: from /home/amiedes/.rbenv/versions/2.6.5/bin/bankscrap:23:in `load'
	17: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-2.1.1/bin/bankscrap:5:in `<top (required)>'
	16: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	15: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	14: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	12: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-2.1.1/lib/bankscrap/cli.rb:78:in `transactions'
	11: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-2.1.1/lib/bankscrap/cli.rb:118:in `initialize_client_for'
	10: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-2.1.1/lib/bankscrap/cli.rb:118:in `new'
	 9: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-bbva-2.0.3/lib/bankscrap/bbva/bank.rb:20:in `initialize'
	 8: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-2.1.1/lib/bankscrap/bank.rb:29:in `initialize'
	 7: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-bbva-2.0.3/lib/bankscrap/bbva/bank.rb:140:in `login'
	 6: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-2.1.1/lib/bankscrap/bank.rb:77:in `with_headers'
	 5: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-bbva-2.0.3/lib/bankscrap/bbva/bank.rb:141:in `block in login'
	 4: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-2.1.1/lib/bankscrap/bank.rb:65:in `post'
	 3: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mechanize-2.7.6/lib/mechanize.rb:511:in `post'
	 2: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mechanize-2.7.6/lib/mechanize.rb:562:in `request_with_entity'
	 1: from /home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bankscrap-bbva-2.0.3/lib/monkey_patch/mechanize.rb:32:in `fetch_with_retry'
/home/amiedes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:329:in `fetch': 500 => Net::HTTPInternalServerError for https://servicios.bbva.es/ENPP/enpp_mult_web_mobility_02/sessions/v1 -- unhandled response (Mechanize::ResponseCodeError)
```

The login procedure seems to be failing [here](https://github.com/bankscrap/bankscrap-bbva/blob/master/lib/bankscrap/bbva/bank.rb#L141-L143). I tested this gem a few days ago and it was working OK. 

I've tried to inspect the traffic with Charles Proxy but I haven't been able to configure the SSL proxy correctly for BBVA, I'm getting the following error:

![image](https://user-images.githubusercontent.com/9287468/72643644-7678c200-396f-11ea-8f85-ce710787b88a.png)

But I've managed to configure it correctly for other hosts:

![image](https://user-images.githubusercontent.com/9287468/72643722-a758f700-396f-11ea-8ee3-e41499d56dd3.png)

**Other information**

- I'm inspecting the traffic from my phone, iPhone Xs

**Questions**

- ¿Can someone confirm if bankscrap bbva is also failing for them?
- ¿Can someone confirm if he/she is able to configure SSL proxying correctly?

**Comment by juansalvatella** [comment]
Yes, it's failing for me as well.

**Comment by raulmarcosl** [comment]
Yes, sadly it's failing, I suspect they have changed something since @javiercr developed the last version of this adapter.

I'll try to take a look in the next weeks, but I don't know how easy it will be to fix this: If they changed completely how the login works, we will have to develop a new adapter. I will keep you posted.

**Comment by juansalvatella** [comment]
Hi Raul! Have you had the chance to have a look at this?
